### ISSUE TITLE
Arial Narrow font issue

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/bipm-si-brochure#143]
The text in quote and the page header render in Arial Narrow Bold Italic font:
![image](https://user-images.githubusercontent.com/5559926/124568890-1705bf00-de4e-11eb-8b2f-b02218f61b9a.png)

**Comment by Intelligent2013** [comment]
fontist_locations.yml:
```yaml
---
Arial:
  Regular:
    full_name: Arial
    paths:
    - C:/Windows/Fonts/arial.ttf
  Bold:
    full_name: Arial Bold
    paths:
    - C:/Windows/Fonts/arialbd.ttf
  Bold Italic:
    full_name: Arial Bold Italic
    paths:
    - C:/Windows/Fonts/arialbi.ttf
  Italic:
    full_name: Arial Italic
    paths:
    - C:/Windows/Fonts/ariali.ttf
  Narrow:
    full_name: Arial Narrow
    paths:
    - C:/Windows/Fonts/ARIALN.TTF
  Narrow Bold:
    full_name: Arial Narrow Bold
    paths:
    - C:/Windows/Fonts/ARIALNB.TTF
  Narrow Bold Italic:
    full_name: Arial Narrow Bold Italic
    paths:
    - C:/Windows/Fonts/ARIALNBI.TTF
  Narrow Italic:
    full_name: Arial Narrow Italic
    paths:
    - C:/Windows/Fonts/ARIALNI.TTF
  Black:
    full_name: Arial Black
    paths:
    - C:/Windows/Fonts/ariblk.ttf
```

mn2pdf font config:
```xml
<font embed-url="file:/C:/Windows/Fonts/arial.ttf" kerning="yes" mn_default="false">
	<font-triplet name="Arial" style="normal" weight="normal"/>
</font>
<font embed-url="file:/C:/Windows/Fonts/arialbd.ttf" kerning="yes" mn_default="false">
	<alternate embed-url="Arial Bold.ttf"/>
	<font-triplet name="Arial" style="normal" weight="bold"/>
</font>
<font embed-url="file:/C:/Windows/Fonts/arialbi.ttf" kerning="yes" mn_default="false">
	<alternate embed-url="Arial Bold Italic.ttf"/>
	<font-triplet name="Arial" style="italic" weight="bold"/>
</font>
<font embed-url="file:/C:/Windows/Fonts/ariali.ttf" kerning="yes" mn_default="false">
	<alternate embed-url="Arial Italic.ttf"/>
	<font-triplet name="Arial" style="italic" weight="normal"/>
</font>
<font embed-url="file:/C:/Users/UserTest/.metanorma/fonts/ariblk.ttf" kerning="yes" mn_default="false">
	<alternate embed-url="Arial Black.ttf"/>
	<font-triplet name="Arial Black" style="normal" weight="normal"/>
</font>
...
<font embed-url="file:/C:/Windows/Fonts/ARIALN.TTF" kerning="yes" mn_default="false">
	<font-triplet name="Arial" style="normal" weight="normal"/>
</font>
<font embed-url="file:/C:/Windows/Fonts/ARIALNB.TTF" kerning="yes" mn_default="false">
	<font-triplet name="Arial" style="normal" weight="normal"/>
</font>
<font embed-url="file:/C:/Windows/Fonts/ARIALNBI.TTF" kerning="yes" mn_default="false">
	<font-triplet name="Arial" style="normal" weight="normal"/>
</font>
<font embed-url="file:/C:/Windows/Fonts/ARIALNI.TTF" kerning="yes" mn_default="false">
	<font-triplet name="Arial" style="italic" weight="normal"/>
</font>
<font embed-url="file:/C:/Windows/Fonts/ariblk.ttf" kerning="yes" mn_default="false">
	<font-triplet name="Arial" style="normal" weight="900"/>
</font>
```

mn2pdf recognizes `Narrow Bold Italic` as `name="Arial" style="normal" weight="normal"`:
```
<font embed-url="file:/C:/Windows/Fonts/ARIALNBI.TTF" kerning="yes" mn_default="false">
	<font-triplet name="Arial" style="normal" weight="normal"/>
</font>
```
and FOP uses last `font` entry with ` name="Arial" style="normal" weight="normal"`, therefore we see `Narrow Bold Italic` font.

Arial and Arial Narrow are two different fonts. We can set font-weight to normal. bold, light, etc., and font-style to italic, normal, but there isn't font-... property to set font modification like normal or narrow.
Charmap (windows) shows Arial Narrow as standalone font:
![image](https://user-images.githubusercontent.com/5559926/124578120-9a2b1300-de56-11eb-97dc-1d103cf33eb9.png)

So, fontist_locations.yml should be:
```yaml
---
Arial:
  Regular:
    full_name: Arial
    paths:
    - C:/Windows/Fonts/arial.ttf
  Bold:
    full_name: Arial Bold
    paths:
    - C:/Windows/Fonts/arialbd.ttf
  Bold Italic:
    full_name: Arial Bold Italic
    paths:
    - C:/Windows/Fonts/arialbi.ttf
  Italic:
    full_name: Arial Italic
    paths:
    - C:/Windows/Fonts/ariali.ttf
  Black:
    full_name: Arial Black
    paths:
    - C:/Windows/Fonts/ariblk.ttf
Arial Narrow:
  Regular:
    full_name: Arial Narrow
    paths:
    - C:/Windows/Fonts/ARIALN.TTF
  Bold:
    full_name: Arial Narrow Bold
    paths:
    - C:/Windows/Fonts/ARIALNB.TTF
  Bold Italic:
    full_name: Arial Narrow Bold Italic
    paths:
    - C:/Windows/Fonts/ARIALNBI.TTF
  Italic:
    full_name: Arial Narrow Italic
    paths:
    - C:/Windows/Fonts/ARIALNI.TTF
```
