### ISSUE TITLE
BIPM final review: Links to BIPM outcomes should follow document language

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/bipm-si-brochure#192]
From BIPM Janet Miles:
> In the links to the Resolutions on the BIPM website, for the French texts the “/en/” in the link should be changed to “/fr/”.

This refers to:
* Issue 12, 40 in #190 

Right now, Relaton does not to provide links for both languages:
* https://github.com/relaton/relaton-data-bipm/blob/9fd0943b7b142a23903bee0a8386463736e1a1af/data/cipm/meeting/resolution/1948-00.yaml#L17

bipm-data-outcomes already provides both language-specific links:
* https://github.com/metanorma/bipm-data-outcomes/blob/main/cipm/meetings-fr/meeting-42.yml

```yaml
metadata:
  title: 42e réunion du CIPM
  identifier: '42'
  date: '1948-10-22'
  source: BIPM - Pavillon de Breteuil
  url: https://www.bipm.org/fr/committees/ci/cipm/42-1948
```

This requires some change in the way Metanorma integrates with Relaton.
Metanorma also needs to include the language-specific link that is intended for the document language.
