### ISSUE TITLE
BIPM final review: Update reference conventions to CIPM/CGPM/CCTF outcomes

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/bipm-si-brochure#193]
From BIPM Janet Miles:

When referring to the Resolutions I’d provided you with the English description but not the French: in French the model for “CGPM Resolution X (YYYY)” would be
* Résolution X **_de la_** CGPM (YYYY)

And there’s another slight complication in that the wording is “**_de la_**” for the CGPM, but “**_du_**” for the CIPM and Consultative Committees:
* Recommandation 2 _**du**_ CCDS (1970)

If this proves problematic we’ll have to find another solution… On the French version of the BIPM website my shortest version of the references is:
* CCTF - Recommandation 2 (1970)

--------

I believe this is a Relaton issue. The data source at bipm-data-outcomes does not provide this text.

In realton-data-bipm, this text is provided:
https://github.com/relaton/relaton-data-bipm/blob/9fd0943b7b142a23903bee0a8386463736e1a1af/data/cipm/meeting/resolution/1948-00.yaml#L26-L40

```yaml
docid:
- id: CIPM Resolution (1948)
  type: BIPM
  primary: true
- id: CIPM Resolution (1948)
  type: BIPM
  primary: true
  language: en
  script: Latn
- id: CIPM Résolution (1948)
  type: BIPM
  primary: true
  language: fr
  script: Latn
docnumber: CIPM Resolution (1948)
```

So this is a task for @andrew2net , and there may be some impact to relator-render (@opoudjis )
