### ISSUE TITLE
(URGENT) Citation issues: Metrologia missing title and all localities (volume, issue)

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/bipm-si-brochure#272]
Data that is provided looks like this:

https://github.com/relaton/relaton-data-bipm/blob/main/data/metrologia-1-1-1.yaml
```yaml
extent:
- locality:
    type: volume
    reference_from: '1'
- locality:
    type: issue
    reference_from: '1'
- locality:
    type: page
    reference_from: '1'
    reference_to: '1'
```

How it looked like before:
![image_2024_12_20T02_36_48_693Z](https://github.com/user-attachments/assets/de8a8d29-988c-4145-a376-d10e52d2dc21)

How it looks like now:

<img width="554" alt="Screenshot 2024-12-20 at 12 31 50 PM" src="https://github.com/user-attachments/assets/1d9fb965-b6a8-4cc2-beb1-2f4e998eb620" />

The data is *correct*. This means that the Metanorma / relaton-render rendering is *incorrect*.

For some very strange reason, @opoudjis 's generation works (except for missing titles):
* [20241220-nn-collection_en.pdf](https://github.com/user-attachments/files/18206013/20241220-nn-collection_en.pdf)
* [20241220-nn-collection_fr.pdf](https://github.com/user-attachments/files/18206016/20241220-nn-collection_fr.pdf)

However, mine (and @andrew2net 's ) doesn't:

Left (me), Right (@opoudjis )
<img width="1131" alt="Screenshot 2024-12-20 at 12 37 32 PM" src="https://github.com/user-attachments/assets/3dec4ec7-8517-4397-807e-2585293490c2" />

Notice these differences:
* Metrologia citations. Looks like something to do with relaton-render.
* CIPM resolution superscript "e" not formatted in the PubID, it is however present in the title. Looks like something to do with relaton-render.
