### ISSUE TITLE
How to configure MN GHA action to only build SI brochure 3.01

### ISSUE THREAD

**Issue by strogonoff** [metanorma/bipm-si-brochure#288]
This is what typical GHA build would looks like:

```
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Print Metanorma version
        run: metanorma --version

      - name: Cache or generate Metanorma XML
        uses: actions-mn/build-and-publish@v2
        with:
          agree-to-terms: true
          destination: artifact
          artifact-name: mn
          cache-extra-input: |
            sources/si-brochure/3.01/**
          cache-site-for-manifest: metanorma.yml
```

But I want to create a workflow that only builds SI 3.01.

Locally I run `bundle exec metanorma collection --agree-to-terms sources/si-brochure/3.01/collection.yml`. How to make Metanorma Docker GHA action do the same?

**Comment by ronaldtse** [comment]
You can check the options available in the action:
* https://github.com/actions-mn/build-and-publish/blob/main/action.yml

The easy way is to create a new manifest file that only points to the SI Brochure collection:

```yaml
  config-file:
    description: 'Metanorma configuration (mainfest) file'
    default: metanorma.yml
```

1. Change the content of `https://github.com/metanorma/bipm-si-brochure/blob/main/brochure.yml` to point to the latest 3.x collection.

2. Create a workflow with this action:

```yaml
      - name: Cache or generate Metanorma XML
        uses: actions-mn/build-and-publish@v2
        with:
          agree-to-terms: true
          config-file: brochure.yml   # <== added
          destination: artifact
          artifact-name: brochure    # <== changed
          cache-extra-input: |
            sources/si-brochure/3.01/**
          cache-site-for-manifest: brochure.yml    # <== changed
```
